openapi: 3.1.0
info:
  title: Mattrax Platform
  description: |
    Hello World!
  version: 1.0.0
servers:
  - url: https://playground.otbeaumont.me
paths:
  '/planets':
    get:
      summary: Get all device
      description: Devices do device things!
      operationId: getAllData
      security:
        - {}
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
